// Generated by gencpp from file hri_navigation/Goal.msg
// DO NOT EDIT!


#ifndef HRI_NAVIGATION_MESSAGE_GOAL_H
#define HRI_NAVIGATION_MESSAGE_GOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hri_navigation
{
template <class ContainerAllocator>
struct Goal_
{
  typedef Goal_<ContainerAllocator> Type;

  Goal_()
    : X(0)
    , Y(0)  {
    }
  Goal_(const ContainerAllocator& _alloc)
    : X(0)
    , Y(0)  {
    }



   typedef uint32_t _X_type;
  _X_type X;

   typedef uint32_t _Y_type;
  _Y_type Y;




  typedef boost::shared_ptr< ::hri_navigation::Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hri_navigation::Goal_<ContainerAllocator> const> ConstPtr;

}; // struct Goal_

typedef ::hri_navigation::Goal_<std::allocator<void> > Goal;

typedef boost::shared_ptr< ::hri_navigation::Goal > GoalPtr;
typedef boost::shared_ptr< ::hri_navigation::Goal const> GoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hri_navigation::Goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hri_navigation::Goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hri_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hri_navigation': ['/home/ted/catkin_ws/src/hri_navigation/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hri_navigation::Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_navigation::Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_navigation::Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_navigation::Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_navigation::Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_navigation::Goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hri_navigation::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1f2aebb6961d1330665be5194655a79";
  }

  static const char* value(const ::hri_navigation::Goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1f2aebb6961d133ULL;
  static const uint64_t static_value2 = 0x0665be5194655a79ULL;
};

template<class ContainerAllocator>
struct DataType< ::hri_navigation::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hri_navigation/Goal";
  }

  static const char* value(const ::hri_navigation::Goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hri_navigation::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 X\n\
uint32 Y\n\
";
  }

  static const char* value(const ::hri_navigation::Goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hri_navigation::Goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hri_navigation::Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hri_navigation::Goal_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.Y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRI_NAVIGATION_MESSAGE_GOAL_H
